version: 2

sources: 
  - name: gz_raw_data
    description: raw data from Circle
    tables: 
      - name: product
        identifier: raw_gz_product
        description: purchase price for all product_id
      - name: sales
        identifier: raw_gz_sales
        description: orders informations
      - name: ship
        identifier: raw_gz_ship
        description: shipping information