version: 2

sources: 
  - name: gz_raw_data
    description: raw data from Circle
    tables: 
      - name: product
        identifier: raw_gz_product
        description: purchase price for all product_id
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: products price
      - name: sales
        freshness: 
          warn_after: {count: 90, period: day}
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        identifier: raw_gz_sales
        description: orders informations
        columns:
          - name: data_date
            description: purchase date
          - name: orders_id
            description: orders id 
          - name: pdt_id
            description: products id
          - name: revenue
            description: orders total price 
          - name: quantity
            description: products daty purchased
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"
      - name: ship
        identifier: raw_gz_ship
        description: shipping information
        columns:
          - name: orders_id
            description: orders id
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: shipping cost
          - name: logcost
            description: logcost
          - name: ship_cost
            description: ship cost
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords informations
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: clef de la campagne
          - name: camPGN_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impressions
          - name: click
            description: nombre de clicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: bing
        identifier: raw_gz_bing
        description: bing informations
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: clef de la campagne
          - name: camPGN_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impressions
          - name: click
            description: nombre de clicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo informations
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: clef de la campagne
          - name: camPGN_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impressions
          - name: click
            description: nombre de clicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook informations
        columns:
          - name: date_date
            description: date
          - name: paid_source
            description: source du paiement
          - name: campaign_key
            description: clef de la campagne
          - name: camPGN_name
            description: nom de la campagne
          - name: ads_cost
            description: coût de la campagne
          - name: impression
            description: nombre d'impressions
          - name: click
            description: nombre de clicks
        tests:
          - unique:
              column_name: "(date_date || '_' || campaign_key)"

models:
  - name: int_sales_margin
    description: margin calcultation per order line / product sale
    columns:
      - name: "(orders_id || '_' || products_id)"
        description: primary key
        tests:
          - unique
      - name: orders_id
        tests:
          - not_null
      - name: products_id
        tests:
          - not_null
      - name: margin
        description: Margin = Revenue - Purchase_cost
        tests:
          - not_null
      - name: purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
        tests:
          - not_null
      - name: date_date
        description: xxxxxxxxx
        tests:
          - not_null
      - name: revenue
        description: xxxxxxxx
        tests:
          - not_null
      - name: quantity
        description: xxxxxx
        tests:
          - not_null

  - name: int_orders_margin
    description: margin calcultation per order 
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
      - name: date_date
        description: date of the order
        tests:
          - not_null
      - name: revenue
        description: sum of revenue per order 
        tests:
          - not_null
      - name: quantity
        description: sum of quantity per order
        tests:
          - not_null
      - name: purchase_cost
        description: Purchase_cost = Quantity * Purchase_price 
        tests:
          - not_null
      - name: margin
        description: Margin = Revenue - Purchase_cost
        tests:
          - not_null

  - name: int_orders_operational
    description: operational margin calcultation per order
    columns:
      - name: orders_id
        description: primary key
        tests:
          - unique
      - name: date_date
        tests:
          - not_null
      - name: operational_margin
        tests:
          - not_null
      - name: quantity
        tests:
          - not_null
      - name: purchase_cost
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: margin
        tests:
          - not_null
      - name: shipping_fee
        tests:
          - not_null
      - name: logcost
        tests:
          - not_null
      - name: ship_cost
        tests:
          - not_null

  - name: finance_days
    description: finance calculation per days 
    columns:
      - name: date_date
        description: primary key
        tests:
          - unique
      - name: nb_transaction
        tests:
          - not_null
      - name: revenue
        tests:
          - not_null
      - name: average_basket
        tests:
          - not_null
      - name: margin
        tests:
          - not_null
      - name: operational_margin
        tests:
          - not_null

  - name: int_campaings
    description: data from all campaigns
    columns:
      - name: "(date_date || '_' || campaign_key)"
        description: primary key
        tests:
          - unique
      - name: paid_source
        description: source du paiement
        tests:
          - not_null
      - name: campaign_name
        description: nom de la campagne
        tests:
          - not_null
      - name: ads_cost
        description: coût de la campagne
        tests:
          - not_null
      - name: impression
        description: nombre d'impressions
        tests:
          - not_null
      - name: click
        description: nombre de clicks
        tests:
          - not_null
      - name: date_date
        description: date
        tests:
          - not_null

  - name: int_campaings_days
    description: regroupe les coûts des ads par jours
    columns:
      - name: date_date
        tests:
          - unique
      - name: ads_cost
        description: xxx
        tests:
          - not_null
      - name: ads_impression
        description: xxx
        tests:
          - not_null
      - name: ads_clicks
        description: xxx
        tests:
          - not_null